language: java
  
jobs:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: openjdk8
    - os: linux
      dist: bionic
      jdk: openjdk8
    - os: osx
      osx_image: xcode9.3
        
script:
 - mvn enforcer:display-info
 - mvn test verify install -B 
  
after_success:
 - bash <(curl -s https://codecov.io/bash)
