version: '{build}'
image:
 - Visual Studio 2019
 - Visual Studio 2017
 - Visual Studio 2015
 - Visual Studio 2013
build_script:
  - mvn clean package --batch-mode -DskipTests
test_script:
  - mvn -Djna.nosys=true test verify --batch-mode
after_test:
 - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
 - pip install codecov
 - codecov -f "system-tests/target/site/jacoco-aggregate/jacoco.xml"
cache:
  - C:\Users\appveyor\.m2
